# MoDL 2020
# Tensor Representation of Fully Connected Neural Networks

In [1]:
import sympy as sp
import numpy as np
import torch

In [2]:
def sig(x): #sigmoid activation function
    return 1/(1+np.exp(-x))

Let's first look at the representation of a fully connected network with no hidden layers. We'd have a weight matrix. Below is a neural net with three input and two output layers. 

In [3]:
W = np.array([[0.4,0.3,0.3],[0.2,0.5,0.3]]) #weight matrix
x = np.array([[0.6],[0.4],[0.5]]).reshape(3,1) #input values

In [4]:
p = W@x

In [5]:
y = [sig(float(p[i])) for i in range(len(p))] 
y #output values

[0.6248064744684293, 0.6153837563911821]

We now look at the representation of a fully connected network with two hidden layers. The input layer has 10 nodes, the hidden layers each have 20 nodes, and the output layer has three nodes.

In [35]:
x = np.random.uniform(-1,1,10).reshape(10,1) #input

W1 = np.random.uniform(0,1,200).reshape(20,10) #weights corresponding to first hidden layer

W2 = np.random.uniform(0,1,400).reshape(20,20) #weights corresponding to second hidden layer

W3 = np.random.uniform(0,1,60).reshape(3,20) #weights corresponding to the output layer


In [33]:
def tanh(arr): #hyperbolic tangent activation function whose input is an array
    return (1-np.exp(-2*arr))/(1+np.exp(-2*arr))

def ReLu(arr): #ReLu activation function whsoe input is an array
    out = np.array([np.max([0,arr[i][0]]) for i in range(len(arr))]).reshape(len(arr),1)
    return out
    

def SoftMax(arr): #SoftMax function whose input is an array
    return np.exp(arr) / float(sum(np.exp(arr)))

In [36]:
h1 = tanh(W1@x) #input to the first hidden layer after tanh activation
h1

array([[ 0.42166536],
       [-0.03602757],
       [ 0.16906935],
       [ 0.2182613 ],
       [-0.54506423],
       [ 0.16403491],
       [-0.34890632],
       [ 0.02628274],
       [ 0.25615976],
       [-0.38270639],
       [ 0.06941713],
       [ 0.22373832],
       [-0.30081665],
       [-0.37444577],
       [-0.0119336 ],
       [ 0.09038233],
       [ 0.17227576],
       [-0.24508553],
       [ 0.33577998],
       [-0.00172484]])

In [37]:
h2 = ReLu(W2@h1) #input to the second hidden layer after ReLu activation
h2

array([[0.53832149],
       [0.        ],
       [0.21715411],
       [0.26443456],
       [0.        ],
       [0.25585572],
       [0.1753095 ],
       [0.00330432],
       [0.        ],
       [0.        ],
       [0.04267007],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.35357084],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ]])

In [42]:
y = SoftMax(W3@h2)
print("Output : y = \n{}".format(y))

Output : y = 
[[0.41114087]
 [0.27802768]
 [0.31083144]]
