# MoDL 2020
# Tensor Decompositions

In [1]:
import numpy as np
import torch
from torch import tensor
import tensorly as tl

Using numpy backend.


### SIngular Value Decomposition of Matrices

In [13]:
np.random.seed(33)
m, n = 5,4
A = np.random.normal(size=m*n).reshape(m,n)
svd = tl.partial_svd(A,np.min([m,n]))

print("U = \n {} \n".format(svd[0]))
print("Singular values : {} \n".format(svd[1]))
print("V = \n {} \n".format(svd[2]))
      
#svd decomposes a matrix into a sum of rank-1 matrices
      

U = 
 [[-0.29138844  0.94917399  0.05347178 -0.07484443]
 [ 0.52654931  0.06905377  0.50942166 -0.66065109]
 [-0.21559343 -0.13960283  0.09503138  0.10160935]
 [-0.76705603 -0.27342376  0.24443866 -0.49293439]
 [-0.05461791 -0.00712802  0.81783196  0.55193267]] 

Singular values : [3.32173961 2.21104604 1.98390941 0.41060727] 

V = 
 [[ 0.01929839 -0.10121144  0.39258143  0.91392759]
 [-0.13245706 -0.83865241 -0.51209803  0.1298956 ]
 [-0.46301086  0.51450218 -0.6365405   0.34018325]
 [-0.87618699 -0.14732915  0.42243534 -0.17927314]] 



### CP Decomposition of Tensors

In [30]:
np.random.seed(33)
T = np.around(np.random.normal(size=24).reshape(2,3,4),2)
T

#CP decomposition is the higher dimensional analogue of SVD

array([[[-0.32, -1.6 , -1.54, -0.57],
        [-0.22,  0.25, -0.15,  2.01],
        [-0.1 ,  0.42, -0.23, -0.64]],

       [[-0.02,  1.04, -1.08, -2.21],
        [-0.95,  0.83, -1.  ,  0.34],
        [ 1.55,  0.69, -2.05,  0.33]]])

In [46]:
I,J,K  = T.shape[0],T.shape[1],T.shape[2]

cp = tl.decomposition.parafac(T,np.min([I*J,I*K,J*K]))

print("A = \n {} \n".format(np.around(cp[0],2)))
print("B = \n {} \n".format(np.around(cp[1],2)))
print("C = \n {} \n".format(np.around(cp[2],2)))

A = 
 [[-1.27 -0.66  0.56 -0.44  0.05 -0.  ]
 [-3.06 -2.29 -0.49 -0.7   0.04  0.93]] 

B = 
 [[-7.10e-01  1.10e-01 -2.49e+00  6.20e-01 -9.79e+00  3.00e-02]
 [-2.00e-02 -8.00e-02 -1.17e+00 -6.00e-02  2.37e+01 -1.89e+00]
 [-5.70e-01 -9.60e-01  5.90e-01  3.50e-01 -2.60e+00  1.20e+00]] 

C = 
 [[  1.94  -0.04  -0.21   9.76  -0.57   0.46]
 [  0.29   0.2    0.91   0.87   0.71   0.26]
 [ -3.66   0.16   1.07 -13.67   0.87   0.95]
 [  0.22   0.11  -0.56   3.35   1.36   0.46]] 



### Tucker Decomposition of Tensors

In [50]:
tk = tl.decomposition.tucker(T)

print("Core G = \n {} \n".format(np.around(tk[0],2)))
print("Prinicipal Component A = \n {} \n".format(np.around(tk[1][0],2)))
print("Prinicipal Component B = \n {} \n".format(np.around(tk[1][1],2)))
print("Prinicipal Component C = \n {} \n".format(np.around(tk[1][2],2)))

#Tucker decomposition is the higher dimensional equivalent of PCA

Core G = 
 [[[-3.1  -0.29  0.07 -0.12]
  [-0.26 -2.27  0.52 -0.36]
  [ 0.35  0.35  0.11 -1.58]]

 [[-0.19 -0.07 -1.88 -0.36]
  [ 0.85  0.12  0.78 -0.24]
  [ 1.14 -1.51 -0.62  0.2 ]]] 

Prinicipal Component A = 
 [[ 0.34  0.94]
 [ 0.94 -0.34]] 

Prinicipal Component B = 
 [[-0.93  0.29 -0.24]
 [-0.   -0.64 -0.76]
 [-0.38 -0.71  0.6 ]] 

Prinicipal Component C = 
 [[ 0.14  0.29 -0.11 -0.94]
 [ 0.18  0.17 -0.95  0.2 ]
 [-0.64 -0.66 -0.29 -0.26]
 [-0.73  0.67  0.    0.1 ]] 

